### ISSUE TITLE
System.ArgumentException: An item with the same key has already been added. Key: ot-Span

### ISSUE THREAD

**Issue by YuriiNskyi** [opentracing-contrib/csharp-netcore#63]
Hello, seems that [this issue](https://github.com/opentracing-contrib/csharp-netcore/issues/51) was fixed, however there is still a problem in version 0.6.2. Here's a full stack trace of the error:

> System.ArgumentException: An item with the same key has already been added. Key: ot-Span
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at OpenTracing.Contrib.NetCore.CoreFx.HttpHandlerDiagnostics.OnNext(String eventName, Object arg)
   at OpenTracing.Contrib.NetCore.Internal.DiagnosticListenerObserver.System.IObserver<System.Collections.Generic.KeyValuePair<System.String,System.Object>>.OnNext(KeyValuePair`2 value)

What else should I do, if I'm already using version 0.6.2?

**Comment by cwe1ss** [comment]
Fixed in v0.7.0+
